2022-07-01 14:47:48 | ERROR |  | Path:/api/Test/W104,输入参数:,IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 57
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 14:50:04 | ERROR |  | Path:/api/Test/W104,输入参数:,IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 57
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 15:02:42 | ERROR |  | Path:/api/Test/W104,输入参数:,IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 57
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 16:28:22 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:29:27 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:40:48 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:44:52 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:45:18 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:48:50 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:52:43 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 16:59:09 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 17:04:11 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
2022-07-01 17:10:49 | ERROR |  | Path:/api/Test/W104,输入参数:{sysUser:{"UserId":1111,"UserCode":"3の2","UserName":"dafdag","UserPwd":"gadadga","UserPwdTimesTamp":"string","UserStatus":0,"LastLoginTime":"2022-07-01T09:09:21.035Z","JobId":0,"AddTime":"2022-07-01T09:09:21.035Z","PhoneNumber":"string","CompanyName":"string","Valid":0};},IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
