2022-07-01 17:19:15 | ERROR |  | Path:/api/Test/W104,输入参数:{sysUser:{"UserId":0,"UserCode":"string","UserName":"string","UserPwd":"string","UserPwdTimesTamp":"string","UserStatus":0,"LastLoginTime":"2022-07-01T09:18:32.587Z","JobId":0,"AddTime":"2022-07-01T09:18:32.587Z","PhoneNumber":"string","CompanyName":"string","Valid":0};},IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 17:19:55 | ERROR |  | Path:/api/Test/W104,输入参数:{sysUser:{"UserId":0,"UserCode":"string","UserName":"string","UserPwd":"string","UserPwdTimesTamp":"string","UserStatus":0,"LastLoginTime":"2022-07-01T09:19:51.592Z","JobId":0,"AddTime":"2022-07-01T09:19:51.592Z","PhoneNumber":"string","CompanyName":"string","Valid":0};},IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 17:20:40 | ERROR |  | Path:/api/Test/W105,输入参数:?id=1,IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUserById(Int32 id) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 68
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 17:29:55 | ERROR |  | Path:/api/Test/W104,输入参数:{sysUser:{"UserId":0,"UserCode":"string","UserName":"string","UserPwd":"string","UserPwdTimesTamp":"string","UserStatus":0,"LastLoginTime":"2022-07-01T09:28:35.075Z","JobId":0,"AddTime":"2022-07-01T09:28:35.075Z","PhoneNumber":"string","CompanyName":"string","Valid":0};},IP:localhost:7166-->System.DivideByZeroException：Attempted to divide by zero.——异常堆栈信息：   at Focus.WebApi.Controllers.TestController.GetSysUser(SysUser sysUser) in D:\oym\Project\Focus\Focus.WebApi\Focus.WebApi\Controllers\TestController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) |  | ResourceInvoker.InvokeFilterPipelineAsync => ResourceInvoker.Next => CustomerExceptionFilter.OnExceptionAsync
2022-07-01 17:30:59 | ERROR |  | An unhandled exception has occurred while executing the request. |  | AsyncMethodBuilderCore.Start => <Invoke>d__9.MoveNext => DiagnosticsLoggerExtensions.UnhandledException
